#
dataselenium:
  extends:
    file: docker-compose-common.yml
    service: dataselenium

# run lettuce tests via selenium hub on test stack (see external_links)
lettucehost:
  image: muccg/yabi-dev
  command: lettuce
  environment:
    - DBUSER=yabiapp
    - WAIT_FOR_RUNSERVER=1
  volumes_from:
    - dataselenium
  external_links:
    - yabi_runservertest_1:web
    - yabi_seleniumhub_1:hub
