version: '2'
services:

  #
  datadevselenium:
    extends:
      file: docker-compose-common.yml
      service: datadevselenium
     
  #
  dataprodselenium:
    extends:
      file: docker-compose-common.yml
      service: dataprodselenium

  # runs the lettuce tests against docker-compose-teststack.yml
  teststack:
    image: muccg/yabi-dev
    command: lettuce
    environment:
       - WAIT_FOR_RUNSERVER=1
       - WAIT_FOR_QUEUE=1
       - WAIT_FOR_DB=1
       - WAIT_FOR_CACHE=1
       - WAIT_FOR_SSH=1
       - WAIT_FOR_S3=1
       - ALLOWED_HOSTS=*
       - RUNSERVER=runservertest
       - CELERYSERVER=celerytest
       - CACHESERVER=cachetest
       - DBSERVER=dbtest
       - SSHSERVER=sshtest
       - QUEUESERVER=mqtest
       - S3SERVER=s3test
    volumes_from:
      - datadevselenium

  # runs the lettuce tests against docker-compose-prod.yml
  prod:
    image: muccg/yabi-dev
    command: lettuce
    environment:
       - WAIT_FOR_UWSGI=1
       - WAIT_FOR_QUEUE=1
       - WAIT_FOR_DB=1
       - WAIT_FOR_CACHE=1
       - WAIT_FOR_SSH=1
       - WAIT_FOR_S3=1
       - ALLOWED_HOSTS=*
       - TEST_APP_HOST=nginxtest
       - TEST_APP_PORT=443
       - TEST_APP_SCHEME=https
       - TEST_APP_PATH=/app/
       - RUNSERVER=runservertest
       - CELERYSERVER=celerytest
       - CACHESERVER=cachetest
       - DBSERVER=dbtest
       - SSHSERVER=sshtest
       - QUEUESERVER=mqtest
       - S3SERVER=s3test
    volumes_from:
      - dataprodselenium
