seleniumhub:
  image: selenium/hub
  ports:
    - "4444"

chrome:
  image: selenium/node-chrome
  volumes:
    - /dev/shm:/dev/shm
  links:
  - seleniumhub:hub

firefox:
  image: selenium/node-firefox
  volumes:
    - /dev/shm:/dev/shm
  links:
  - seleniumhub:hub
